public class User {

    // variables

    private String userId;
    private String username;

    // Constructor

    public User(String userId, String username) {
        this.userId = userId;
        this.user = username;
    }

    
    // Setters

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public setUsername(String username) {
        this.username = username;
    }

    // Getters

    public String getUserId() {
        return userid;
    }

    public string getUsername() {
        return username;
    }
}